services:
  ordering:
    image: ordering
    build:
      context: .
      dockerfile: Ordering/Dockerfile
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "!sqlTest201"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"