services:
  ordering:
    image: ordering
    build:
      context: .
      dockerfile: OutboxPlayground/Dockerfile
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "!sqlTest201"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"