@Ordering_HostAddress = http://localhost:5018

GET {{Ordering_HostAddress}}/api/Courses
Accept: application/json

###

GET {{Ordering_HostAddress}}/api/Courses/00000000-0000-0000-0000-000000000001
Accept: application/json

###

POST {{Ordering_HostAddress}}/api/Courses
Content-Type: application/json

{
  "name": "New Course",
  "description": "Course description",
  "reviews": [
    {
      "rating": 5,
      "comment": "Great course!"
    }
  ]
}

###

PUT {{Ordering_HostAddress}}/api/Courses/00000000-0000-0000-0000-000000000001
Content-Type: application/json

{
  "id": "00000000-0000-0000-0000-000000000001",
  "name": "Updated Course",
  "description": "Updated description",
  "reviews": []
}

###

DELETE {{Ordering_HostAddress}}/api/Courses/00000000-0000-0000-0000-000000000001